### ISSUE TITLE
Где хранятся файлы портала? 

### ISSUE THREAD

**Issue by Pum-purum** [akopkesheshyan/bitrix24-docker#3]
Запустил портал согласно инструкции на сайте. Папка с docker-compose.yml содержит только этот  файл, и больше никаких других. Но где теперь файлы портала?

**Comment by vilyus** [comment]
Если я правильно понимаю, то после `docker-compose up` в папке c `docker-compose.yml` и веб-инсталляции текущая директория заполнится файлами из папки `%CONTAINER_APP_ROOT%/local`.

Данная настрйока в файле `docker-compose.yml`:
```yml
services:
  web:
    volumes:
      - ./:/home/bitrix/www/local
```
означает, что текущая директория будет объединена с директорией `/home/bitrix/www/local/` с помощью механизма Volumes докера: https://docs.docker.com/storage/volumes/

Это значит, что все файлы, добавленные в папку `local` в ходе веб-инсталляции также будут добавлены в текущую директорию (корень проекта на хост-машине).

**Comment by ilyazverev1988** [comment]
Как я понял, по замыслу автора, содержимое /home/bitrix/www/local должно быть расположено рядом композником, в этой же папке. Но этого не происходит и данные размещаются в слое докер контейнера. Что не так?
